---
- name: Universal Ping Test
  hosts: all
  gather_facts: yes  # need facts to detect OS

  tasks:
    - name: Ping Linux hosts
      ansible.builtin.ping:
      when: ansible_os_family != "Windows"

    - name: Ping Windows hosts
      win_ping:
      when: ansible_os_family == "Windows"
