---
- name: Bulk unattended install on MacOS hosts via AWX
  hosts: MacBook-Air
  become: true
  gather_facts: true

  tasks:
    - name: Copy Mac installation script to host
      copy:
        src: files/install_mac.sh
        dest: /tmp/install_mac.sh
        mode: '0755'

    - name: Run Mac installation script
      command: /tmp/install_mac.sh
      args:
        creates: /opt/mac_system_upgraded
