---
- name: Bulk unattended install on Windows hosts via AWX
  hosts: windows
  gather_facts: false

  tasks:
    - name: Copy Windows installation script
      win_copy:
        src: files/install_windows.ps1
        dest: C:\Windows\Temp\install_windows.ps1

    - name: Run Windows installation script
      win_shell: |
        powershell.exe -ExecutionPolicy Bypass -File C:\Windows\Temp\install_windows.ps1
      args:
        creates: C:\Windows\Temp\windows_system_upgraded
