---
- name: Bulk unattended install on MacOS hosts
  hosts: MacBook_Air
  gather_facts: true
  # DO NOT use become: true

  tasks:
    - name: Copy Mac installation script
      copy:
        src: files/install_mac.sh
        dest: /tmp/install_mac.sh
        mode: '0755'

    - name: Run Mac installation script
      command: /tmp/install_mac.sh
