---
- name: Bulk unattended update & upgrade on RHEL hosts via AWX
  hosts: all
  become: true
  gather_facts: true

  vars:
    log_file: /var/log/unattended_install_rhel.log
    marker_file: /opt/rhel_system_upgraded

  tasks:
    - name: Copy RHEL update script to target host
      copy:
        src: files/install_rhel.sh
        dest: /tmp/install_rhel.sh
        mode: '0755'

    - name: Run RHEL update script and log output
      shell: |
        echo "==============================" >> {{ log_file }}
        echo "RHEL Update started: $(date)" >> {{ log_file }}
        echo "==============================" >> {{ log_file }}
        /tmp/install_rhel.sh >> {{ log_file }} 2>&1
        echo "RHEL Update finished: $(date)" >> {{ log_file }}
        touch {{ marker_file }}
      args:
        creates: "{{ marker_file }}"
