---
- name: Bulk unattended install on Debian hosts via AWX
  hosts: all
  become: true
  gather_facts: true

  vars:
    log_file: /var/log/unattended_install.log
    marker_file: /opt/system_upgraded

  tasks:
    - name: Ensure log directory exists
      file:
        path: /var/log
        state: directory
        mode: '0755'

    - name: Copy install script to target host
      copy:
        src: files/install_debian.sh
        dest: /tmp/install_debian.sh
        mode: '0755'

    - name: Run installation script and capture output
      shell: |
        unset DISPLAY
        chmod +x /tmp/install_debian.sh
        /tmp/install_debian.sh
      args:
        creates: "{{ marker_file }}"
      register: script_output

    - name: Write script output to log with markers
      copy:
        content: |
          ==============================
          Installation started: {{ ansible_date_time.date }} {{ ansible_date_time.time }}
          ==============================
          {{ script_output.stdout_lines | join('\n') }}
          Installation completed: {{ ansible_date_time.date }} {{ ansible_date_time.time }}
        dest: "{{ log_file }}"
        owner: root
        group: root
        mode: '0644'
