---
- name: Bulk unattended update & upgrade on MacOS hosts
  hosts: MacBook_Air
  gather_facts: true
  # DO NOT use become: true on macOS

  vars:
    log_file: "{{ ansible_env.HOME }}/unattended_install_mac.log"

  tasks:
    - name: Copy Mac update script
      copy:
        src: files/install_mac.sh
        dest: /tmp/install_mac.sh
        mode: '0755'

    - name: Run update & upgrade script and log output
      shell: |
        {
          echo "=============================="
          echo "MacOS Update started: $(date)"
          echo "=============================="
          /tmp/install_mac.sh
          echo "MacOS Update finished: $(date)"
        } >> {{ log_file }} 2>&1
