---
- name: Bulk unattended update & upgrade on RHEL hosts via AWX
  hosts: all
  become: true
  gather_facts: true

  vars:
    log_file: /var/log/unattended_install_rhel.log

  tasks:
    - name: Copy RHEL update script to target host
      copy:
        src: files/install_rhel.sh
        dest: /tmp/install_rhel.sh
        mode: '0755'

    - name: Run RHEL update script and log output
      shell: |
        unset DISPLAY
        chmod +x /tmp/install_rhel.sh
        {
          echo "=============================="
          echo "RHEL Update started: $(date)"
          echo "=============================="
          /tmp/install_rhel.sh
          echo "RHEL Update finished: $(date)"
        } >> {{ log_file }} 2>&1
