---
- name: Bulk unattended update & upgrade on Windows hosts via AWX
  hosts: all
  gather_facts: false

  vars:
    log_file: C:\Windows\Temp\unattended_install_windows.log

  tasks:
    - name: Copy Windows update script
      win_copy:
        src: files/install_windows.ps1
        dest: C:\Windows\Temp\install_windows.ps1

    - name: Run Windows update script and log output
      win_shell: |
        Set-ExecutionPolicy Unrestricted -Scope Process -Force

        # Ensure script is not blocked
        Unblock-File -Path C:\Windows\Temp\install_windows.ps1 -ErrorAction SilentlyContinue

        # Start log
        Add-Content -Path "{{ log_file }}" -Value "=============================="
        Add-Content -Path "{{ log_file }}" -Value "Windows Update started: $(Get-Date)"
        Add-Content -Path "{{ log_file }}" -Value "=============================="

        # Run script and capture all output
        powershell.exe -ExecutionPolicy Bypass -File C:\Windows\Temp\install_windows.ps1 *>> "{{ log_file }}"

        # End log
        Add-Content -Path "{{ log_file }}" -Value "Windows Update finished: $(Get-Date)"
        Add-Content -Path "{{ log_file }}" -Value "=============================="
