---
- name: Bulk unattended update & upgrade on Windows hosts via AWX
  hosts: all
  gather_facts: false

  vars:
    log_file: C:\Windows\Temp\unattended_install_windows.log
    marker_file: C:\Windows\Temp\windows_system_upgraded

  tasks:
    - name: Copy Windows update script
      win_copy:
        src: files/install_windows.ps1
        dest: C:\Windows\Temp\install_windows.ps1

    - name: Run Windows update script and log output
      win_shell: |
        powershell.exe -ExecutionPolicy Bypass -Command "
          Add-Content -Path '{{ log_file }}' -Value '=============================='
          Add-Content -Path '{{ log_file }}' -Value 'Windows Update started: ' + (Get-Date)
          Add-Content -Path '{{ log_file }}' -Value '=============================='

          powershell.exe -ExecutionPolicy Bypass -File C:\Windows\Temp\install_windows.ps1 *>> '{{ log_file }}'

          Add-Content -Path '{{ log_file }}' -Value 'Windows Update finished: ' + (Get-Date)
          New-Item -ItemType File -Path '{{ marker_file }}' -Force
        "
      args:
        creates: "{{ marker_file }}"
